### ISSUE TITLE
LRU forward pass in case of dense linear transition matrix instead of diagonal transition matrix

### ISSUE THREAD

**Issue by talrub** [NicolasZucchet/minimal-LRU#3]
Hi,
First of all thanks for this great implementation of the LRU presented in  Orvieto et al. 2023.
I am wondering how would you implement the model's forward pass function in case we are using a linear RNN with real and dense transition matrix 'A' (instead of a complex diagonal one that is used in the final LRU version).
Is using parallel_scan will still be possible?
If the answer to my question is yes can you reply here with the implementation to this case?
If the answer is no, how would you implement it in a way it will be more efficient than non linear RNN ( in Orvieto et al. 2023 it is mentioned that moving from non linear RNN to linear RNN should allows us to parallelize training, but if we are not using parallel scan i don't see how the forward pass speed will be different between non linear and linear RNNs).

Thanks,
Tal

**Comment by NicolasZucchet** [comment]
Hello,
Unfortunately, using parallel scan will not work anymore.
Prior work to the LRU used non-diagonal recurrence connectivity matrix such as S4. The trick here is to transform the recurrent layer into a convolutional layer, for more detail see e.g. https://srush.github.io/annotated-s4/.

Hope this is useful!
Nicolas
